export const ar = {
    Today: "اليوم",
    Updated: "آخر تحديث: ",
    HourlyTitle: 'التوقعات الجوية كل ساعة',
    DailyTitle: 'العنوان اليومي',
    Feels: 'ستشعر كأنه/يبدو كأنه',
    MinMax: 'دقيقة/الأعلى',
    Sunrise: "شروق الشمس: ",
    Sunset: "غروب الشمس: ",
    Morn: "صباحاً",
    Noon: "وقت الظهيرة",
    Eve: "مساءً",
    Night: "ليلاً",
    Max: "الأعلى",
    Min: "دقيقة",
    Settings: "الإعدادات",
    Units: "الوحدات",
    TemperatureUnit: "وحدة درجة الحرارة",
    Celsius: "مئوية",
    Fahrenheit: "فهرنهايت",
    TimeFormat: "صيغة الوقت",
    Format12Hour: "12 ساعة",
    Format24Hour: "24 ساعة",
    AutoFormat: "تلقائي",
    Locations: "المواقع",
    CurrentLocation: "الموقع الحالي",
    AddLocation: "إضافة موقع",
    SearchLocation: "ابحث عن مدينة...",
    NoResults: "لم يتم العثور على مواقع",
    MaxLocationsReached: "الحد الأقصى %{count} مواقع محفوظة",
    DuplicateLocation: "تمت إضافة هذا الموقع بالفعل",
    StartTyping: "ابدأ الكتابة للبحث...",
    Searching: "جاري البحث...",
    WidgetStyle: "نمط الأداة",
    WidgetThemeIndigo: "نيلي",
    WidgetThemeMidnight: "منتصف الليل",
    EnableLocation: "تفعيل الموقع",
    UseCurrentLocation: "استخدام الموقع الحالي",
    Locating: "جارٍ تحديد الموقع...",
    NoLocationTitle: "لا يوجد موقع بعد",
    NoLocationDescription: "أضف مدينة لعرض حالة الطقس فيها. لا حاجة لتفعيل الوصول إلى الموقع.",
    DeleteLocation: "حذف الموقع",
    DeleteLocationConfirm: "هل أنت متأكد أنك تريد حذف",
    Cancel: "إلغاء",
    Delete: "حذف",
    Language: "اللغة",
    AppLanguage: "لغة التطبيق",
    ShowSunriseSunset: "إظهار شروق/غروب الشمس",
    Show: "إظهار",
    Hide: "إخفاء",
    // Error messages
    Error: "خطأ",
    Retry: "إعادة المحاولة",
    OpenSettings: "فتح الإعدادات",
    OK: "موافق",
    // Error taxonomy (localized at render via AppError.userMessageKey; these keys
    // are referenced by string literal in src/utils/errors.ts, NOT via i18n.t('...'))
    ErrNetwork: "تعذّر الاتصال بالإنترنت",
    ErrNoConnection: "لا يوجد اتصال بالإنترنت. يرجى التحقق من إعدادات الشبكة.",
    ErrTimeout: "استغرق الطلب وقتًا طويلاً. يرجى المحاولة مرة أخرى.",
    ErrApiGeneric: "حدث خطأ أثناء جلب البيانات",
    ErrRateLimit: "طلبات كثيرة جدًا. يرجى التمهّل والمحاولة مرة أخرى.",
    ErrServer: "تواجه خوادمنا مشكلات. يرجى المحاولة مرة أخرى بعد قليل.",
    ErrNotFound: "تعذّر العثور على البيانات المطلوبة. يرجى المحاولة مرة أخرى.",
    ErrBadRequest: "طلب غير صالح. يرجى التحقق من إدخالك والمحاولة مرة أخرى.",
    ErrAuth: "خدمة الطقس غير متاحة مؤقتًا. يرجى المحاولة لاحقًا.",
    ErrPermissionDenied: "الوصول إلى الموقع معطّل. فعّله لاستخدام موقعك الحالي، أو أضف مدينة يدويًا.",
    ErrLocationUnavailable: "تعذّر تحديد موقعك. تأكد من تفعيل نظام تحديد المواقع (GPS).",
    ErrPositionTimeout: "تحديد موقعك يستغرق وقتًا طويلاً. يرجى المحاولة مرة أخرى.",
    ErrUnexpected: "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.",
    ErrGeneric: "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
    // Error & loading screens
    ErrorTitle: "تعذّر تحميل الطقس",
    ErrorDefaultMessage: "تعذّر جلب بيانات الطقس. يرجى التحقق من اتصالك والمحاولة مرة أخرى.",
    ErrorSupport: "إذا تكرر هذا كثيرًا، يرجى التواصل مع الدعم على",
    BannerSupport: "إذا تكرر هذا كثيرًا، تواصل مع %{email} للحصول على المساعدة.",
    LoadingTitle: "جارٍ تحميل الطقس...",
    LoadingMessage: "جارٍ جلب التوقعات لـ %{location}",
    // Widget chrome
    WidgetUnavailable: "بيانات الطقس غير متاحة",
    WidgetTapToRetry: "اضغط لإعادة المحاولة",
    WidgetRefreshing: "جارٍ التحديث...",
    WidgetLoadError: "تعذّر تحميل الطقس",
    WidgetRefreshError: "تعذّر التحديث",
    WidgetUV: "UV",
    WidgetHi: "عظمى",
    WidgetLo: "صغرى",
    WidgetAgeMinutes: "قبل %{count} د",
    WidgetAgeHours: "قبل %{count} س",
    WidgetAgeDays: "قبل %{count} ي",
}