export const ar = {
    Today: "اليوم",
    Updated: "آخر تحديث: ",
    Title: "النشرة الجوية",
    PoweredBy: "التشفير الجيوغرافي العكسي المُشغّل من قبل ",
    Geoapify: "Geoapify",
    ProvidedBy: "بيانات حالة الطقس مقدمة من ",
    OpenWeather: "OpenWeather",
    HourlyTitle: 'التوقعات الجوية كل ساعة',
    DailyTitle: 'العنوان اليومي',
    Feels: 'ستشعر كأنه/يبدو كأنه',
    MinMax: 'دقيقة/الأعلى',
    Sunrise: "شروق الشمس: ",
    Sunset: "غروب الشمس: ",
    Morn: "صباحاً",
    Noon: "وقت الظهيرة",
    Eve: "مساءً",
    Night: "ليلاً",
    Max: "الأعلى",
    Min: "دقيقة",
    SpeedInfo: "كم/ساعة",
    SpeedInfoImp: "ميلا في الساعة",
    Settings: "الإعدادات",
    Units: "الوحدات",
    TemperatureUnit: "وحدة درجة الحرارة",
    Celsius: "مئوية",
    Fahrenheit: "فهرنهايت",
    Close: "إغلاق",
    Locations: "المواقع",
    CurrentLocation: "الموقع الحالي",
    AddLocation: "إضافة موقع",
    SearchLocation: "ابحث عن مدينة...",
    SearchResults: "نتائج البحث",
    NoResults: "لم يتم العثور على مواقع",
    LocationAdded: "تمت إضافة الموقع",
    LocationRemoved: "تمت إزالة الموقع",
    MaxLocationsReached: "الحد الأقصى 5 مواقع محفوظة",
    StartTyping: "ابدأ الكتابة للبحث...",
    Searching: "جاري البحث...",
    SearchError: "فشل البحث. حاول مرة أخرى.",
    DeleteLocation: "حذف الموقع",
    DeleteLocationConfirm: "هل أنت متأكد أنك تريد حذف",
    Cancel: "إلغاء",
    Delete: "حذف",
    Language: "اللغة",
    AppLanguage: "لغة التطبيق",
    AutoDetect: "الكشف التلقائي (لغة الجهاز)",
    // Error messages
    Error: "خطأ",
    Retry: "إعادة المحاولة",
    OpenSettings: "فتح الإعدادات",
    OK: "موافق",
}