export const en = {
    Today: "Today",
    Updated: "Last Updated: ",
    HourlyTitle: 'Hourly Forecast',
    DailyTitle: 'Daily Forecast',
    Feels: 'Feels Like',
    MinMax: 'Min/Max',
    Sunrise: "Sunrise: ",
    Sunset: "Sunset: ",
    Morn: "Morn",
    Noon: "Noon",
    Eve: "Eve",
    Night: "Night",
    Max: "Max",
    Min: "Min",
    Settings: "Settings",
    Units: "Units",
    TemperatureUnit: "Temperature Unit",
    Celsius: "Celsius",
    Fahrenheit: "Fahrenheit",
    TimeFormat: "Time Format",
    Format12Hour: "12 Hour",
    Format24Hour: "24 Hour",
    AutoFormat: "Auto",
    Locations: "Locations",
    CurrentLocation: "Current Location",
    AddLocation: "Add Location",
    SearchLocation: "Search for a city...",
    NoResults: "No locations found",
    MaxLocationsReached: "Maximum %{count} locations saved",
    DuplicateLocation: "This location has already been added",
    StartTyping: "Start typing to search...",
    Searching: "Searching...",
    WidgetStyle: "Widget Style",
    WidgetThemeIndigo: "Indigo",
    WidgetThemeMidnight: "Midnight",
    WidgetThemeSlate: "Slate",
    WidgetThemePlum: "Plum",
    WidgetThemeForest: "Forest",
    WidgetThemeMaroon: "Maroon",
    EnableLocation: "Enable Location",
    UseCurrentLocation: "Use Current Location",
    Locating: "Locating...",
    NoLocationTitle: "No location yet",
    NoLocationDescription: "Add a city to see its weather. You don't need to turn on location access.",
    DeleteLocation: "Delete Location",
    DeleteLocationConfirm: "Are you sure you want to delete",
    Cancel: "Cancel",
    Delete: "Delete",
    Language: "Language",
    AppLanguage: "App Language",
    ShowSunriseSunset: "Show Sunrise/Sunset",
    Show: "Show",
    Hide: "Hide",
    // Error messages
    Error: "Error",
    Retry: "Retry",
    OpenSettings: "Open Settings",
    OK: "OK",
    // Error taxonomy (localized at render via AppError.userMessageKey; these keys
    // are referenced by string literal in src/utils/errors.ts, NOT via i18n.t('...'))
    ErrNetwork: "Unable to connect to the internet",
    ErrNoConnection: "No internet connection. Please check your network settings.",
    ErrTimeout: "The request took too long. Please try again.",
    ErrApiGeneric: "An error occurred while fetching data",
    ErrRateLimit: "Too many requests. Please slow down and try again.",
    ErrServer: "Our servers are experiencing issues. Please try again in a moment.",
    ErrNotFound: "The requested data was not found. Please try again.",
    ErrBadRequest: "Invalid request. Please check your input and try again.",
    ErrAuth: "Weather service is temporarily unavailable. Please try again later.",
    ErrPermissionDenied: "Location access is off. Turn it on to use your current location, or add a city manually instead.",
    ErrLocationUnavailable: "Unable to determine your location. Make sure GPS is enabled.",
    ErrPositionTimeout: "Finding your location is taking too long. Please try again.",
    ErrUnexpected: "An unexpected error occurred. Please try again.",
    ErrGeneric: "Something went wrong. Please try again.",
    // Error & loading screens
    ErrorTitle: "Unable to Load Weather",
    ErrorDefaultMessage: "Unable to fetch weather data. Please check your connection and try again.",
    ErrorSupport: "If this happens often, please contact support at",
    BannerSupport: "If this happens often, contact %{email} for help.",
    LoadingTitle: "Loading Weather...",
    LoadingMessage: "Fetching forecast for %{location}",
    // Widget chrome
    WidgetUnavailable: "Weather data unavailable",
    WidgetTapToRetry: "Tap to retry",
    WidgetRefreshing: "Refreshing...",
    WidgetLoadError: "Unable to load weather",
    WidgetRefreshError: "Unable to refresh",
    WidgetHi: "Hi",
    WidgetLo: "Lo",
    WidgetAgeMinutes: "%{count}m ago",
    WidgetAgeHours: "%{count}h ago",
    WidgetAgeDays: "%{count}d ago",
}