export const en = {
    Today: "Today",
    Updated: "Last Updated: ",
    Title: "Weather Forecast",
    PoweredBy: "Reverse geocoding powered by ",
    Geoapify: "Geoapify",
    ProvidedBy: "Weather data provided by ",
    OpenWeather: "OpenWeather",
    HourlyTitle: 'Hourly Forecast',
    DailyTitle: 'Daily Forecast',
    Feels: 'Feels Like',
    MinMax: 'Min/Max',
    Sunrise: "Sunrise: ",
    Sunset: "Sunset: ",
    Morn: "Morn",
    Noon: "Noon",
    Eve: "Eve",
    Night: "Night",
    Max: "Max",
    Min: "Min",
    SpeedInfo: "km/h",
    SpeedInfoImp: "mph",
}