export const en = {
    Today: "Today",
    Updated: "Last Updated: ",
    Title: "Weather Forecast",
    PoweredBy: "Reverse geocoding powered by ",
    Geoapify: "Geoapify",
    ProvidedBy: "Weather data provided by ",
    OpenWeather: "OpenWeather",
    HourlyTitle: 'Hourly Forecast',
    DailyTitle: 'Daily Forecast',
    Feels: 'Feels Like',
    MinMax: 'Min/Max',
    Sunrise: "Sunrise: ",
    Sunset: "Sunset: ",
    Morn: "Morn",
    Noon: "Noon",
    Eve: "Eve",
    Night: "Night",
    Max: "Max",
    Min: "Min",
    SpeedInfo: "km/h",
    SpeedInfoImp: "mph",
    Settings: "Settings",
    Units: "Units",
    TemperatureUnit: "Temperature Unit",
    Celsius: "Celsius",
    Fahrenheit: "Fahrenheit",
    TimeFormat: "Time Format",
    Format12Hour: "12 Hour",
    Format24Hour: "24 Hour",
    AutoFormat: "Auto",
    Close: "Close",
    Locations: "Locations",
    CurrentLocation: "Current Location",
    AddLocation: "Add Location",
    SearchLocation: "Search for a city...",
    SearchResults: "Search Results",
    NoResults: "No locations found",
    LocationAdded: "Location added",
    LocationRemoved: "Location removed",
    MaxLocationsReached: "Maximum 5 locations saved",
    StartTyping: "Start typing to search...",
    Searching: "Searching...",
    SearchError: "Failed to search. Try again.",
    DeleteLocation: "Delete Location",
    DeleteLocationConfirm: "Are you sure you want to delete",
    Cancel: "Cancel",
    Delete: "Delete",
    Language: "Language",
    AppLanguage: "App Language",
    AutoDetect: "Auto-detect (Device Language)",
    ShowSunriseSunset: "Show Sunrise/Sunset",
    Show: "Show",
    Hide: "Hide",
    // Error messages
    Error: "Error",
    Retry: "Retry",
    OpenSettings: "Open Settings",
    OK: "OK",
}