export const es = {
    Today: "Hoy",
    Updated: "Última actualización: ",
    Title: "Pronóstico del tiempo",
    PoweredBy: "Geocodificación inversa proporcionado por ",
    Geoapify: "Geoapify",
    ProvidedBy: "Datos meteorológicos proporcionados por ",
    OpenWeather: "OpenWeather",
    HourlyTitle: 'Pronóstico por hora',
    DailyTitle: 'Pronóstico diario',
    Feels: 'Se siente como',
    MinMax: 'Minimo/Maximo',
    Sunrise: "Amanecer",
    Sunset: "Atardecer",
    Morn: "Mañana",
    Noon: "Mediodía",
    Eve: "Tarde",
    Night: "Noche",
    Min: "Minimo",
    Max: "Maximo",
    SpeedInfo: "km/h",
    SpeedInfoImp: "mph",
    Settings: "Ajustes",
    Units: "Unidades",
    TemperatureUnit: "Unidad de Temperatura",
    Celsius: "Celsius",
    Fahrenheit: "Fahrenheit",
    Close: "Cerrar",
    Locations: "Ubicaciones",
    CurrentLocation: "Ubicación Actual",
    AddLocation: "Agregar Ubicación",
    SearchLocation: "Buscar una ciudad...",
    SearchResults: "Resultados de Búsqueda",
    NoResults: "No se encontraron ubicaciones",
    LocationAdded: "Ubicación agregada",
    LocationRemoved: "Ubicación eliminada",
    MaxLocationsReached: "Máximo 5 ubicaciones guardadas",
    StartTyping: "Comienza a escribir para buscar...",
    Searching: "Buscando...",
    SearchError: "Error al buscar. Inténtalo de nuevo.",
    DeleteLocation: "Eliminar Ubicación",
    DeleteLocationConfirm: "¿Estás seguro de que quieres eliminar",
    Cancel: "Cancelar",
    Delete: "Eliminar",
    Language: "Idioma",
    AppLanguage: "Idioma de la Aplicación",
    AutoDetect: "Detectar Automáticamente (Idioma del Dispositivo)",
}