export const es = {
    Today: "Hoy",
    Updated: "Última actualización: ",
    HourlyTitle: 'Pronóstico por hora',
    DailyTitle: 'Pronóstico diario',
    Feels: 'Se siente como',
    MinMax: 'Minimo/Maximo',
    Sunrise: "Amanecer",
    Sunset: "Atardecer",
    Morn: "Mañana",
    Noon: "Mediodía",
    Eve: "Tarde",
    Night: "Noche",
    Min: "Minimo",
    Max: "Maximo",
    Settings: "Ajustes",
    Units: "Unidades",
    TemperatureUnit: "Unidad de Temperatura",
    Celsius: "Celsius",
    Fahrenheit: "Fahrenheit",
    TimeFormat: "Formato de Hora",
    Format12Hour: "12 Horas",
    Format24Hour: "24 Horas",
    AutoFormat: "Auto",
    Locations: "Ubicaciones",
    CurrentLocation: "Ubicación Actual",
    AddLocation: "Agregar Ubicación",
    SearchLocation: "Buscar una ciudad...",
    NoResults: "No se encontraron ubicaciones",
    MaxLocationsReached: "Máximo %{count} ubicaciones guardadas",
    DuplicateLocation: "Esta ubicación ya ha sido agregada",
    StartTyping: "Comienza a escribir para buscar...",
    Searching: "Buscando...",
    EnableLocation: "Activar ubicación",
    NoLocationTitle: "Aún no hay ninguna ubicación",
    NoLocationDescription: "Añade una ciudad para ver su tiempo. No necesitas activar el acceso a la ubicación.",
    DeleteLocation: "Eliminar Ubicación",
    DeleteLocationConfirm: "¿Estás seguro de que quieres eliminar",
    Cancel: "Cancelar",
    Delete: "Eliminar",
    Language: "Idioma",
    AppLanguage: "Idioma de la Aplicación",
    ShowSunriseSunset: "Mostrar Amanecer/Atardecer",
    Show: "Mostrar",
    Hide: "Ocultar",
    // Error messages
    Error: "Error",
    Retry: "Reintentar",
    OpenSettings: "Abrir Configuración",
    OK: "OK",
    // Error taxonomy (localized at render via AppError.userMessageKey; these keys
    // are referenced by string literal in src/utils/errors.ts, NOT via i18n.t('...'))
    ErrNetwork: "No se puede conectar a internet",
    ErrNoConnection: "Sin conexión a internet. Comprueba la configuración de tu red.",
    ErrTimeout: "La solicitud tardó demasiado. Inténtalo de nuevo.",
    ErrApiGeneric: "Se produjo un error al obtener los datos",
    ErrRateLimit: "Demasiadas solicitudes. Reduce la velocidad e inténtalo de nuevo.",
    ErrServer: "Nuestros servidores tienen problemas. Inténtalo de nuevo en un momento.",
    ErrNotFound: "No se encontraron los datos solicitados. Inténtalo de nuevo.",
    ErrBadRequest: "Solicitud no válida. Comprueba tus datos e inténtalo de nuevo.",
    ErrAuth: "El servicio meteorológico no está disponible temporalmente. Inténtalo de nuevo más tarde.",
    ErrPermissionDenied: "El acceso a la ubicación está desactivado. Actívalo para usar tu ubicación actual o añade una ciudad manualmente.",
    ErrLocationUnavailable: "No se pudo determinar tu ubicación. Asegúrate de que el GPS esté activado.",
    ErrPositionTimeout: "Encontrar tu ubicación está tardando demasiado. Inténtalo de nuevo.",
    ErrUnexpected: "Ocurrió un error inesperado. Inténtalo de nuevo.",
    ErrGeneric: "Algo salió mal. Inténtalo de nuevo.",
    // Error & loading screens
    ErrorTitle: "No se pudo cargar el clima",
    ErrorDefaultMessage: "No se pudieron obtener los datos meteorológicos. Comprueba tu conexión e inténtalo de nuevo.",
    ErrorSupport: "Si esto ocurre a menudo, contacta con soporte en",
    BannerSupport: "Si esto ocurre a menudo, contacta con %{email} para obtener ayuda.",
    LoadingTitle: "Cargando el clima...",
    LoadingMessage: "Obteniendo el pronóstico para %{location}",
    // Widget chrome
    WidgetUnavailable: "Datos meteorológicos no disponibles",
    WidgetTapToRetry: "Toca para reintentar",
    WidgetTapToRefresh: "Toca para actualizar",
    WidgetRefreshing: "Actualizando...",
    WidgetLoadError: "No se pudo cargar el clima",
    WidgetRefreshError: "No se pudo actualizar",
    WidgetHi: "Máx",
    WidgetLo: "Mín",
    WidgetAgeMinutes: "hace %{count} min",
    WidgetAgeHours: "hace %{count} h",
    WidgetAgeDays: "hace %{count} d",
}