export const es = {
    Today: "Hoy",
    Updated: "Última actualización: ",
    Title: "Pronóstico del tiempo",
    PoweredBy: "Geocodificación inversa proporcionado por ",
    Geoapify: "Geoapify",
    ProvidedBy: "Datos meteorológicos proporcionados por ",
    OpenWeather: "OpenWeather",
    HourlyTitle: 'Pronóstico por hora',
    DailyTitle: 'Pronóstico diario',
    Feels: 'Se siente como',
    MinMax: 'Minimo/Maximo',
    Sunrise: "Amanecer",
    Sunset: "Atardecer",
    Morn: "Mañana",
    Noon: "Mediodía",
    Eve: "Tarde",
    Night: "Noche",
    Min: "Minimo",
    Max: "Maximo",
    SpeedInfo: "km/h",
    SpeedInfoImp: "mph",
}