export const fr = {
    Today: "Aujourd'hui",
    Updated: "Dernière mise à jour : ",
    Title: "Météo",
    PoweredBy: "Géocodage inversé avec ",
    Geoapify: "Geoapify",
    ProvidedBy: "Données météorologiques fournies par ",
    OpenWeather: "OpenWeather",
    HourlyTitle: 'Heure par heure',
    DailyTitle: 'Semaine',
    Feels: 'Ressentie',
    MinMax: 'Min/Max',
    Sunrise: "Lever : ",
    Sunset: "Coucher : ",
    Morn: "Matin",
    Noon: "Midi",
    Eve: "Soir",
    Night: "Nuit",
    Max: "Max",
    Min: "Min",
    SpeedInfo: "km/h",
    SpeedInfoImp: "mph",
    Settings: "Paramètres",
    Units: "Unités",
    TemperatureUnit: "Unité de Température",
    Celsius: "Celsius",
    Fahrenheit: "Fahrenheit",
    Close: "Fermer",
    Locations: "Emplacements",
    CurrentLocation: "Position Actuelle",
    AddLocation: "Ajouter un Emplacement",
    SearchLocation: "Rechercher une ville...",
    SearchResults: "Résultats de Recherche",
    NoResults: "Aucun emplacement trouvé",
    LocationAdded: "Emplacement ajouté",
    LocationRemoved: "Emplacement supprimé",
    MaxLocationsReached: "Maximum 5 emplacements enregistrés",
    StartTyping: "Commencez à taper pour rechercher...",
    Searching: "Recherche...",
    SearchError: "Échec de la recherche. Réessayez.",
    DeleteLocation: "Supprimer l'Emplacement",
    DeleteLocationConfirm: "Êtes-vous sûr de vouloir supprimer",
    Cancel: "Annuler",
    Delete: "Supprimer",
    Language: "Langue",
    AppLanguage: "Langue de l'Application",
    AutoDetect: "Détection Automatique (Langue de l'Appareil)",
    // Error messages
    Error: "Erreur",
    Retry: "Réessayer",
    OpenSettings: "Ouvrir les Paramètres",
    OK: "OK",
}
