export const fr = {
    Today: "Aujourd'hui",
    Updated: "Dernière mise à jour : ",
    HourlyTitle: 'Heure par heure',
    DailyTitle: 'Semaine',
    Feels: 'Ressentie',
    MinMax: 'Min/Max',
    Sunrise: "Lever : ",
    Sunset: "Coucher : ",
    Morn: "Matin",
    Noon: "Midi",
    Eve: "Soir",
    Night: "Nuit",
    Max: "Max",
    Min: "Min",
    Settings: "Paramètres",
    Units: "Unités",
    TemperatureUnit: "Unité de Température",
    Celsius: "Celsius",
    Fahrenheit: "Fahrenheit",
    TimeFormat: "Format d'Heure",
    Format12Hour: "12 Heures",
    Format24Hour: "24 Heures",
    AutoFormat: "Auto",
    Locations: "Emplacements",
    CurrentLocation: "Position Actuelle",
    AddLocation: "Ajouter un Emplacement",
    SearchLocation: "Rechercher une ville...",
    NoResults: "Aucun emplacement trouvé",
    MaxLocationsReached: "Maximum %{count} emplacements enregistrés",
    DuplicateLocation: "Cet emplacement a déjà été ajouté",
    StartTyping: "Commencez à taper pour rechercher...",
    Searching: "Recherche...",
    EnableLocation: "Activer la localisation",
    NoLocationTitle: "Aucun lieu pour l'instant",
    NoLocationDescription: "Ajoutez une ville pour voir sa météo. Pas besoin d'activer l'accès à la localisation.",
    DeleteLocation: "Supprimer l'Emplacement",
    DeleteLocationConfirm: "Êtes-vous sûr de vouloir supprimer",
    Cancel: "Annuler",
    Delete: "Supprimer",
    Language: "Langue",
    AppLanguage: "Langue de l'Application",
    ShowSunriseSunset: "Afficher Lever/Coucher du Soleil",
    Show: "Afficher",
    Hide: "Masquer",
    // Error messages
    Error: "Erreur",
    Retry: "Réessayer",
    OpenSettings: "Ouvrir les Paramètres",
    OK: "OK",
    // Error taxonomy (localized at render via AppError.userMessageKey; these keys
    // are referenced by string literal in src/utils/errors.ts, NOT via i18n.t('...'))
    ErrNetwork: "Impossible de se connecter à Internet",
    ErrNoConnection: "Pas de connexion Internet. Vérifiez vos paramètres réseau.",
    ErrTimeout: "La requête a pris trop de temps. Veuillez réessayer.",
    ErrApiGeneric: "Une erreur s'est produite lors de la récupération des données",
    ErrRateLimit: "Trop de requêtes. Veuillez ralentir et réessayer.",
    ErrServer: "Nos serveurs rencontrent des problèmes. Veuillez réessayer dans un instant.",
    ErrNotFound: "Les données demandées sont introuvables. Veuillez réessayer.",
    ErrBadRequest: "Requête invalide. Veuillez vérifier votre saisie et réessayer.",
    ErrAuth: "Le service météo est temporairement indisponible. Veuillez réessayer plus tard.",
    ErrPermissionDenied: "L'accès à la localisation est désactivé. Activez-le pour utiliser votre position actuelle, ou ajoutez une ville manuellement.",
    ErrLocationUnavailable: "Impossible de déterminer votre position. Assurez-vous que le GPS est activé.",
    ErrPositionTimeout: "La localisation prend trop de temps. Veuillez réessayer.",
    ErrUnexpected: "Une erreur inattendue s'est produite. Veuillez réessayer.",
    ErrGeneric: "Une erreur s'est produite. Veuillez réessayer.",
    // Error & loading screens
    ErrorTitle: "Impossible de charger la météo",
    ErrorDefaultMessage: "Impossible de récupérer les données météo. Vérifiez votre connexion et réessayez.",
    ErrorSupport: "Si cela se produit souvent, contactez le support à",
    BannerSupport: "Si cela se produit souvent, contactez %{email} pour obtenir de l'aide.",
    LoadingTitle: "Chargement de la météo...",
    LoadingMessage: "Récupération des prévisions pour %{location}",
    // Widget chrome
    WidgetUnavailable: "Données météo indisponibles",
    WidgetTapToRetry: "Touchez pour réessayer",
    WidgetTapToRefresh: "Touchez pour actualiser",
    WidgetRefreshing: "Actualisation...",
    WidgetLoadError: "Impossible de charger la météo",
    WidgetRefreshError: "Impossible d'actualiser",
    WidgetHi: "Max",
    WidgetLo: "Min",
    WidgetAgeMinutes: "il y a %{count} min",
    WidgetAgeHours: "il y a %{count} h",
    WidgetAgeDays: "il y a %{count} j",
}
