export const fr = {
    Today: "Aujourd'hui",
    Updated: "Dernière mise à jour : ",
    Title: "Météo",
    PoweredBy: "Géocodage inversé avec ",
    Geoapify: "Geoapify",
    ProvidedBy: "Données météorologiques fournies par ",
    OpenWeather: "OpenWeather",
    HourlyTitle: 'Heure par heure',
    DailyTitle: 'Semaine',
    Feels: 'Ressentie',
    MinMax: 'Min/Max',
    Sunrise: "Lever : ",
    Sunset: "Coucher : ",
    Morn: "Matin",
    Noon: "Midi",
    Eve: "Soir",
    Night: "Nuit",
    Max: "Max",
    Min: "Min",
    SpeedInfo: "km/h",
    SpeedInfoImp: "mph",
}
