export const he = {
    Today: "היום",
    Updated: "עודכן ",
    HourlyTitle: 'תחזית שעתית',
    DailyTitle: 'תחזית לימים הקרובים',
    Feels: 'מרגיש כמו',
    MinMax: 'טווח טמפ׳',
    Sunrise: "זריחה: ",
    Sunset: "שקיעה: ",
    Morn: "בוקר",
    Noon: "צהריים",
    Eve: "ערב",
    Night: "לילה",
    Max: "מקסימום",
    Min: "מינימום",
    Settings: "הגדרות",
    Units: "יחידות",
    TemperatureUnit: "יחידת טמפרטורה",
    Celsius: "צלזיוס",
    Fahrenheit: "פרנהייט",
    TimeFormat: "פורמט שעה",
    Format12Hour: "12 שעות",
    Format24Hour: "24 שעות",
    AutoFormat: "אוטומטי",
    Locations: "מיקומים",
    CurrentLocation: "מיקום נוכחי",
    AddLocation: "הוסף מיקום",
    SearchLocation: "חפש עיר...",
    NoResults: "לא נמצאו מיקומים",
    MaxLocationsReached: "מקסימום %{count} מיקומים שמורים",
    DuplicateLocation: "מיקום זה כבר נוסף",
    StartTyping: "התחל להקליד כדי לחפש...",
    Searching: "מחפש...",
    WidgetStyle: "סגנון הווידג'ט",
    WidgetThemeIndigo: "אינדיגו",
    WidgetThemeMidnight: "חצות",
    WidgetThemeSlate: "צפחה",
    WidgetThemePlum: "שזיף",
    WidgetThemeForest: "יער",
    WidgetThemeMaroon: "בורדו",
    EnableLocation: "הפעל מיקום",
    UseCurrentLocation: "השתמש במיקום הנוכחי",
    Locating: "מאתר מיקום...",
    NoLocationTitle: "עדיין אין מיקום",
    NoLocationDescription: "הוסף עיר כדי לראות את מזג האוויר שלה. אין צורך להפעיל גישה למיקום.",
    DeleteLocation: "מחק מיקום",
    DeleteLocationConfirm: "האם אתה בטוח שברצונך למחוק",
    Cancel: "ביטול",
    Delete: "מחק",
    Language: "שפה",
    AppLanguage: "שפת האפליקציה",
    ShowSunriseSunset: "הצג זריחה/שקיעה",
    Show: "הצג",
    Hide: "הסתר",
    // Error messages
    Error: "שגיאה",
    Retry: "נסה שוב",
    OpenSettings: "פתח הגדרות",
    OK: "אישור",
    // Error taxonomy (localized at render via AppError.userMessageKey; these keys
    // are referenced by string literal in src/utils/errors.ts, NOT via i18n.t('...'))
    ErrNetwork: "לא ניתן להתחבר לאינטרנט",
    ErrNoConnection: "אין חיבור לאינטרנט. אנא בדוק את הגדרות הרשת.",
    ErrTimeout: "הבקשה ארכה זמן רב מדי. אנא נסה שוב.",
    ErrApiGeneric: "אירעה שגיאה בעת אחזור הנתונים",
    ErrRateLimit: "יותר מדי בקשות. אנא האט ונסה שוב.",
    ErrServer: "השרתים שלנו נתקלים בבעיות. אנא נסה שוב בעוד רגע.",
    ErrNotFound: "הנתונים המבוקשים לא נמצאו. אנא נסה שוב.",
    ErrBadRequest: "בקשה לא תקינה. אנא בדוק את הקלט ונסה שוב.",
    ErrAuth: "שירות מזג האוויר אינו זמין באופן זמני. אנא נסה שוב מאוחר יותר.",
    ErrPermissionDenied: "הגישה למיקום כבויה. הפעל אותה כדי להשתמש במיקום הנוכחי, או הוסף עיר באופן ידני.",
    ErrLocationUnavailable: "לא ניתן לקבוע את מיקומך. ודא שה-GPS מופעל.",
    ErrPositionTimeout: "איתור מיקומך אורך זמן רב מדי. אנא נסה שוב.",
    ErrUnexpected: "אירעה שגיאה בלתי צפויה. אנא נסה שוב.",
    ErrGeneric: "משהו השתבש. אנא נסה שוב.",
    // Error & loading screens
    ErrorTitle: "לא ניתן לטעון את מזג האוויר",
    ErrorDefaultMessage: "לא ניתן לאחזר את נתוני מזג האוויר. אנא בדוק את החיבור ונסה שוב.",
    ErrorSupport: "אם זה קורה לעיתים קרובות, אנא פנה לתמיכה בכתובת",
    BannerSupport: "אם זה קורה לעיתים קרובות, פנה אל %{email} לעזרה.",
    LoadingTitle: "טוען מזג אוויר...",
    LoadingMessage: "מאחזר תחזית עבור %{location}",
    // Widget chrome
    WidgetUnavailable: "נתוני מזג אוויר אינם זמינים",
    WidgetTapToRetry: "הקש כדי לנסות שוב",
    WidgetRefreshing: "מרענן...",
    WidgetLoadError: "לא ניתן לטעון מזג אוויר",
    WidgetRefreshError: "לא ניתן לרענן",
    WidgetHi: "מקס",
    WidgetLo: "מינ",
    WidgetAgeMinutes: "לפני %{count} ד׳",
    WidgetAgeHours: "לפני %{count} ש׳",
    WidgetAgeDays: "לפני %{count} י׳",
}