export const he = {
    Today: "היום",
    Updated: "עודכן ",
    Title: "מזג האוויר",
    PoweredBy: "קידוד גיאוגרפי הפוך מופעל על ידי ",
    Geoapify: "Geoapify",
    ProvidedBy: "נתוני מזג אוויר מסופקים על ידי ",
    OpenWeather: "OpenWeather",
    HourlyTitle: 'תחזית שעתית',
    DailyTitle: 'תחזית לימים הקרובים',
    Feels: 'מרגיש כמו',
    MinMax: 'טווח טמפ׳',
    Sunrise: "זריחה: ",
    Sunset: "שקיעה: ",
    Morn: "בוקר",
    Noon: "צהריים",
    Eve: "ערב",
    Night: "לילה",
    Max: "מקסימום",
    Min: "מינימום",
    SpeedInfo: "קמ\"ש",
    SpeedInfoImp: "מי\"ש",
    Settings: "הגדרות",
    Units: "יחידות",
    TemperatureUnit: "יחידת טמפרטורה",
    Celsius: "צלזיוס",
    Fahrenheit: "פרנהייט",
    Close: "סגור",
    Locations: "מיקומים",
    CurrentLocation: "מיקום נוכחי",
    AddLocation: "הוסף מיקום",
    SearchLocation: "חפש עיר...",
    SearchResults: "תוצאות חיפוש",
    NoResults: "לא נמצאו מיקומים",
    LocationAdded: "המיקום נוסף",
    LocationRemoved: "המיקום הוסר",
    MaxLocationsReached: "מקסימום 5 מיקומים שמורים",
    StartTyping: "התחל להקליד כדי לחפש...",
    Searching: "מחפש...",
    SearchError: "החיפוש נכשל. נסה שוב.",
    DeleteLocation: "מחק מיקום",
    DeleteLocationConfirm: "האם אתה בטוח שברצונך למחוק",
    Cancel: "ביטול",
    Delete: "מחק",
    Language: "שפה",
    AppLanguage: "שפת האפליקציה",
    AutoDetect: "זיהוי אוטומטי (שפת המכשיר)",
    // Error messages
    Error: "שגיאה",
    Retry: "נסה שוב",
    OpenSettings: "פתח הגדרות",
    OK: "אישור",
}