export const zh = {
  Today: "今天",
  Updated: "最新更新于: ",
  Title: "天气预报",
  PoweredBy: "反向地理编码提供由： ",
  Geoapify: "Geoapify",
  HourlyTitle: "每小时预报",
  DailyTitle: "全天预报",
  Feels: "体感",
  MinMax: "最低/最高",
  Sunrise: "日出时间: ",
  Sunset: "日落时间: ",
  Morn: "早",
  Noon: "中",
  Eve: "傍晚",
  Night: "夜晚",
  Max: "最高",
  Min: "最低",
  SpeedInfo: "千米/小时",
  SpeedInfoImp: "迈",
  Settings: "设置",
  Units: "单位",
  TemperatureUnit: "温度单位",
  Celsius: "摄氏度",
  Fahrenheit: "华氏度",
  TimeFormat: "时间格式",
  Format12Hour: "12小时制",
  Format24Hour: "24小时制",
  AutoFormat: "自动",
  Close: "关闭",
  Locations: "地点",
  CurrentLocation: "当前位置",
  AddLocation: "添加地点",
  SearchLocation: "搜索城市...",
  SearchResults: "搜索结果",
  NoResults: "未找到地点",
  LocationAdded: "地点已添加",
  LocationRemoved: "地点已删除",
  MaxLocationsReached: "最多保存%{count}个地点",
  DuplicateLocation: "该地点已添加",
  StartTyping: "开始输入以搜索...",
  Searching: "搜索中...",
  SearchError: "搜索失败。请重试。",
  DeleteLocation: "删除地点",
  DeleteLocationConfirm: "您确定要删除",
  Cancel: "取消",
  Delete: "删除",
  Language: "语言",
  AppLanguage: "应用语言",
  AutoDetect: "自动检测（设备语言）",
  ShowSunriseSunset: "显示日出/日落",
  Show: "显示",
  Hide: "隐藏",
  // Error messages
  Error: "错误",
  Retry: "重试",
  OpenSettings: "打开设置",
  OK: "确定",
  // Error taxonomy (localized at render via AppError.userMessageKey; these keys
  // are referenced by string literal in src/utils/errors.ts, NOT via i18n.t('...'))
  ErrNetwork: "无法连接到互联网",
  ErrNoConnection: "没有网络连接。请检查您的网络设置。",
  ErrTimeout: "请求超时。请重试。",
  ErrApiGeneric: "获取数据时出错",
  ErrRateLimit: "请求过于频繁。请稍后再试。",
  ErrServer: "我们的服务器出现问题。请稍后重试。",
  ErrNotFound: "未找到请求的数据。请重试。",
  ErrBadRequest: "请求无效。请检查您的输入并重试。",
  ErrAuth: "天气服务暂时不可用。请稍后再试。",
  ErrPermissionDenied: "需要位置访问权限。请在设备设置中启用。",
  ErrLocationUnavailable: "无法确定您的位置。请确保已启用 GPS。",
  ErrPositionTimeout: "定位时间过长。请重试。",
  ErrUnexpected: "发生意外错误。请重试。",
  ErrGeneric: "出了点问题。请重试。",
  // Error & loading screens
  ErrorTitle: "无法加载天气",
  ErrorDefaultMessage: "无法获取天气数据。请检查您的网络连接并重试。",
  ErrorSupport: "如果经常发生这种情况，请联系支持：",
  BannerSupport: "如果经常发生这种情况，请联系 %{email} 寻求帮助。",
  LoadingTitle: "正在加载天气...",
  LoadingMessage: "正在获取 %{location} 的预报",
  // Widget chrome
  WidgetUnavailable: "天气数据不可用",
  WidgetTapToRetry: "点按以重试",
  WidgetRefreshing: "正在刷新...",
  WidgetLoadError: "无法加载天气",
  WidgetRefreshError: "无法刷新",
  WidgetHi: "高",
  WidgetLo: "低",
  WidgetAgeMinutes: "%{count} 分钟前",
  WidgetAgeHours: "%{count} 小时前",
  WidgetAgeDays: "%{count} 天前",
};
