export const zh = {
  Today: "今天",
  Updated: "最新更新于: ",
  Title: "天气预报",
  PoweredBy: "反向地理编码提供由： ",
  Geoapify: "Geoapify",
  ProvidedBy: "天气数据提供由： ",
  OpenWeather: "OpenWeather",
  HourlyTitle: "每小时预报",
  DailyTitle: "全天预报",
  Feels: "体感",
  MinMax: "最低/最高",
  Sunrise: "日出时间: ",
  Sunset: "日落时间: ",
  Morn: "早",
  Noon: "中",
  Eve: "傍晚",
  Night: "夜晚",
  Max: "最高",
  Min: "最低",
  SpeedInfo: "千米/小时",
  SpeedInfoImp: "迈",
  Settings: "设置",
  Units: "单位",
  TemperatureUnit: "温度单位",
  Celsius: "摄氏度",
  Fahrenheit: "华氏度",
  TimeFormat: "时间格式",
  Format12Hour: "12小时制",
  Format24Hour: "24小时制",
  AutoFormat: "自动",
  Close: "关闭",
  Locations: "地点",
  CurrentLocation: "当前位置",
  AddLocation: "添加地点",
  SearchLocation: "搜索城市...",
  SearchResults: "搜索结果",
  NoResults: "未找到地点",
  LocationAdded: "地点已添加",
  LocationRemoved: "地点已删除",
  MaxLocationsReached: "最多保存5个地点",
  StartTyping: "开始输入以搜索...",
  Searching: "搜索中...",
  SearchError: "搜索失败。请重试。",
  DeleteLocation: "删除地点",
  DeleteLocationConfirm: "您确定要删除",
  Cancel: "取消",
  Delete: "删除",
  Language: "语言",
  AppLanguage: "应用语言",
  AutoDetect: "自动检测（设备语言）",
  ShowSunriseSunset: "显示日出/日落",
  Show: "显示",
  Hide: "隐藏",
  // Error messages
  Error: "错误",
  Retry: "重试",
  OpenSettings: "打开设置",
  OK: "确定",
};
