export const zh = {
  Today: "今天",
  Updated: "最新更新于: ",
  Title: "天气预报",
  PoweredBy: "反向地理编码提供由： ",
  Geoapify: "Geoapify",
  ProvidedBy: "天气数据提供由： ",
  OpenWeather: "OpenWeather",
  HourlyTitle: "每小时预报",
  DailyTitle: "全天预报",
  Feels: "体感",
  MinMax: "最低/最高",
  Sunrise: "日出时间: ",
  Sunset: "日落时间: ",
  Morn: "早",
  Noon: "中",
  Eve: "傍晚",
  Night: "夜晚",
  Max: "最高",
  Min: "最低",
  SpeedInfo: "千米/小时",
  SpeedInfoImp: "迈",
  Settings: "设置",
  Units: "单位",
  TemperatureUnit: "温度单位",
  Celsius: "摄氏度",
  Fahrenheit: "华氏度",
  Close: "关闭",
};
